### ISSUE TITLE
ambiguous transformer specs

### ISSUE THREAD

**Issue by sanderclaeys** [lanl-ansi/PowerModelsDistribution.jl#118]
I ran into an issue with transformer specs which specify the same model property.

For example, in the defaults dict of a three winding transformer, four properties are always present:
- %r, %r_2, %r_3
- %rs

These values determine the same model properties, but can be mutually inconsistent. If not present in the input file, these properties are set to a default value. This means that it is impossible to know which one was actually specified by the input file, because all properties will be present in the defaults dict. 

In the transformer extension, I use %rs if it is non-zero, and otherwise I use the per winding properties as a workaround. Ideally, the parser should select which of these conflicting properties should apply. For example, if %r, %r_2 and %r_3 are specified by the user, %rs is set to be consistent with them, instead of to a default value.

A similar issue exists for the properties
- %loadloss
- %r, %r_2
- %rs

**Comment by pseudocubic** [comment]
Closed by #162
