### ISSUE TITLE
OpenDSS phases=3 parser bug

### ISSUE THREAD

**Issue by sanderclaeys** [lanl-ansi/PowerModelsDistribution.jl#122]
I encountered a bug for OpenDSS load specifications with `phases=3`.  The parsed  results are three times bigger than they should be. 

I am currently working on an ACP implementation of delta, wye, constant power, constant current and constant impedance loads. All of these are required for common IEEE unbalanced test cases. Related to #10.

I propose to include the fix for this directly in there, rather than in a separate PR. Is that okay for you guys?

For example, take
`new Load.L1 phases=3 kw=5`
This is parsed as a  load with
`pd=[5, 5, 5]`
Whilst the OpenDSS behaviour is
`pd=[5/3, 5/3, 5/3]`

**Comment by pseudocubic** [comment]
Closed by #127
