### ISSUE TITLE
tp_pf voltage magnitude bound

### ISSUE THREAD

**Issue by sanderclaeys** [lanl-ansi/PowerModelsDistribution.jl#125]
In the tp_pf problem formulation, the following constraint should be removed:
https://github.com/lanl-ansi/ThreePhasePowerModels.jl/blob/8abe80da4880382bc5fedaee2dab8e751bdd9733/src/prob/tp_pf.jl#L39
The purpose of this constraint is to enforce the voltage magnitude bounds in the ACR formulation as a SOC constraint. It is empty for the ACP formulation.

It should not be present in the power flow problem. I ran into this issue when debugging the load models.

**Comment by ccoffrin** [comment]
I disagree.  Here is an example of a non-convex problem that requires it, https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/form/act.jl#L15.  Obscure, but worth further exploration.

**Comment by ccoffrin** [comment]
If a specific formulation does not require it, just make an empty function like so, https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/form/acp.jl#L14

**Comment by frederikgeth** [comment]
Ah, ok, I think we may be mixing up two things.

The purpose of `constraint_voltage` is to define KVL over all loops in a meshed network, and thereby reflect the part of the power flow physics that isn't captured by Ohm's law and the conservation of current.

However, for the ACR formulation, this constraint is actuallt used to apply bounds on the voltage magnitude, so voltage magnitude bounds are used, even when solving a power flow (even in PowerModels proper, I think). 

The use of `constraint_voltage` for this purpose seems consistent with the first use case.

**Comment by ccoffrin** [comment]
Oh, I think we are having some confusion due to my lack of documentation.  

My intended semantics for `constraint_voltage` is for constraints that link multiple voltage variables.  For example the bounds in ACR or voltage-based inequalities in the relaxations.  If you wish to do KVL, then I would add new constraint (e.g. `constraint_kvl(...)`) which takes a collection of ordered bus ids which define a cycle in the network graph.

**Comment by sanderclaeys** [comment]
I see. In that case, shouldn't there be a keyword argument 'bounded=false' which deactivates the bound setting for the ACR case? 
Because right now, for the power flow problem formulation, vm>0.9 is enforced for the ACR case, but not the ACP case.

**Comment by ccoffrin** [comment]
Yes!  That is a bug in the current PF formulation.

**Comment by ccoffrin** [comment]
We need an issue or PR on PowerModels to fix this.

**Comment by pseudocubic** [comment]
@ccoffrin was this fixed in PowerModels v0.12?

**Comment by pseudocubic** [comment]
@sanderclaeys @ccoffrin was this issue resolved?

**Comment by ccoffrin** [comment]
Yes, it was here https://github.com/lanl-ansi/PowerModels.jl/pull/498.
