### ISSUE TITLE
no voltage angle information for bf_mx case

### ISSUE THREAD

**Issue by MartaVanin** [lanl-ansi/PowerModelsDistribution.jl#126]
I am running simulations with the linearized BFM, trying to retrieve the voltage angles at the buses from the solution, to check the differences wrt an ACOPF.
To do so, I tried ThreePhasePowerModels.add_original_variables(sol, pm) , from the bf_mx form.
But in place of the angle vector per node, it returns va = [NaN,NaN,NaN].

The reason why it happens is the following:
The off-diagonal entries of the branch flow variable (see sol["branch"]["$l"]["pf_lt"].values and pf_ut) are undefined.

This causes all the following matrix operations involving the S_{ij} matrix result in completely undefined matrices. No errors are thrown but hence the NaNs.
I am not sure how to define those off-diagonal terms to have more sensible results..

**Comment by ccoffrin** [comment]
In this case, I presume the off-diagonal terms should be zero.  Thoughts @frederikgeth?

**Comment by frederikgeth** [comment]
The linearised approximation is built on the assumption that the voltage phase angle differences are 120 degrees. Setting the off-diagonals to zero would not be a very consistent approach. 

You can define consistent off-diagonals as follows:
- S_aa/U_a = S_ba/U_b = S_ca/U_c
- S_ab/U_a = S_bb/U_b = S_cb/U_c
- S_ac/U_a = S_bc/U_b = S_cc/U_c

The linearized formulations include the diagonal elements S_aa, S_bb, S_cc. 
At the reference bus you know the voltage, and then you can propagate from there. But there's no guarantee this recovers meaningful voltage angles.

**Comment by pseudocubic** [comment]
@MartaVanin with all of the changes and bug fixes that have made it to the latest master is this still an issue for you?
