### ISSUE TITLE
`connected_components` doesn't work with transformers feature

### ISSUE THREAD

**Issue by pseudocubic** [lanl-ansi/PowerModelsDistribution.jl#132]
`connected_components` from PowerModels does not work correctly with the addition of transformers. this is due to them existing in `trans` instead of `branch`

There are a couple of ways to go with this:

1. Alter PowerModel's function, perhaps to take arbitrary keys, e.g.:
```julia
function connected_components(data::Dict{String,<:Any}; lines=["branch", "dcline"])
    if InfrastructureModels.ismultinetwork(data)
        Memento.error(LOGGER, "connected_components does not yet support multinetwork data")
    end

    active_bus = Dict(x for x in data["bus"] if x.second["bus_type"] != 4)
    active_bus_ids = Set{Int64}([bus["bus_i"] for (i,bus) in active_bus])

    neighbors = Dict(i => [] for i in active_bus_ids)
    for line_type in lines
        for line in values(get(data, line_type, Dict()))
            if get(line, "br_status", 1) && line["f_bus"] in active_bus_ids && line["t_bus"] in active_bus_ids
                push!(neighbors[line["f_bus"]], line["t_bus"])
                push!(neighbors[line["t_bus"]], line["f_bus"])
            end
        end
    end

    component_lookup = Dict(i => Set{Int64}([i]) for i in active_bus_ids)
    touched = Set{Int64}()

    for i in active_bus_ids
        if !(i in touched)
            _dfs(i, neighbors, component_lookup, touched)
        end
    end

    ccs = (Set(values(component_lookup)))

    return ccs
end
```
2. Create a new `connected_components` function inside ThreePhasePowerModels

I think it would also be possible to further generalize this function and raise it up to InfrastructureModels.

@ccoffrin

**Comment by ccoffrin** [comment]
How about, add a special version to `connected_components` to address this in the near term and add an issue to PowerModels to develop an extendable version of `connected_components`.  Off the top of my head, your proposal seems reasonable.

**Comment by pseudocubic** [comment]
This was resolved in PowerModels.jl
