### ISSUE TITLE
OTS Problem Specification

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModelsDistribution.jl#14]
Formulations Supported
- [ ] Non-Convex AC Polar (ACPPowerModel)
- [ ] Convex SOC WR (SOC WR PowerModel)
- [ ] Linear DistFlow (LDF PowerModel)

**Comment by pseudocubic** [comment]
We will not implement the OTS problem directly, as it is not directly relevant to distribution networks. Another problem specification that will be related will be proposed in the future.
