### ISSUE TITLE
constraint_voltage_angle_difference for AbstractBFForms

### ISSUE THREAD

**Issue by sanderclaeys** [lanl-ansi/PowerModelsDistribution.jl#155]
Reminder to update this method to consider the off-diagonals of the matrix branch shunts. In the current implementation, these are ignored.

**Comment by pseudocubic** [comment]
@sanderclaeys was this addressed in one of the recent updates?

**Comment by sanderclaeys** [comment]
@frederikgeth I think you are the one who addressed this, though I'm not sure anymore.

**Comment by pseudocubic** [comment]
Is this issue still outstanding?
