### ISSUE TITLE
transformer parsing IEEE123 broken

### ISSUE THREAD

**Issue by sanderclaeys** [lanl-ansi/PowerModelsDistribution.jl#174]
IEEE34 now parses correctly, but there still is an issue with the transformer parsing in [IEEE123](https://github.com/sanderclaeys/DistributionTestCases.jl/blob/master/src/data/ieee123/ieee123_pmd.dss). The transformers have tap setting 1.0 everywhere after parsing. This issue does not appear in IEEE34, so I suspect it is caused by the presence of `like` somehow.

Take for example the following lines from IEEE123
```
new transformer.reg4a phases=1          windings=2   bank=reg4     buses=[160.1 160r.1] conns=[wye wye]       kvs=[2.402 2.402] kvas=[2000 2000] XHL=.01 %LoadLoss=0.00001 ppm=0.0
new transformer.reg4b like=reg4a                     bank=reg4     buses=[160.2 160r.2]      ppm=0.0
new transformer.reg4c like=reg4a                     bank=reg4     buses=[160.3 160r.3]      ppm=0.0
Transformer.reg4a.wdg=2 Tap=(0.00625  8 * 1 +)    ! Tap 8
Transformer.reg4b.wdg=2 Tap=(0.00625  1 * 1 +)    ! Tap 1
Transformer.reg4c.wdg=2 Tap=(0.00625  5 * 1 +)    ! Tap 5
```
My reasoning about the cause goes like this.
The transformers after dss parsing have the property `"tap_2"`. However, in `create_transformer`, the kwarg `:wdg_2=>"2"` is missing and therefore the second tap is never applied.

**Comment by pseudocubic** [comment]
Fix in v0.6-rc branch
