### ISSUE TITLE
sourcebus_vbranch c_rating

### ISSUE THREAD

**Issue by sanderclaeys** [lanl-ansi/PowerModelsDistribution.jl#185]
The virtual branch inserted to represent the internal impedance of the sourcebus, does not have any current ratings. This breaks the bf code, which creates a bounded variable for the line current and expects a bound to be present (it rarely works without bounds on matrix variables, so this is intended behaviour)

The sourcebus generator and the sourcebus voltage limits imply a bound on the current as well,
|I| <= Smax./Vmin = sqrt.(max(Pgmax.^2, Pgmin.^2)+max(Qgmax.^2, Qgmin.^2))./Vmin

@frederikgeth does this make sense to you? This is actually only a valid bound on the sourcebus side of the branch; if 'rate_a' is applied symmetrically, this bound is strictly speaking to tight because the other end can have a bigger flow due to the losses.

@pseudocubic do you want to fix this in a separate PR or shall I include it in #150?

**Comment by sanderclaeys** [comment]
I think this does not show up in the existing unit tests because this only happens when loading opendss data, and not when loading the matlab format. Probably the unit tests only load the matlab data where this might throw an error.

**Comment by pseudocubic** [comment]
Closed by #186
