### ISSUE TITLE
oltc by default or not

### ISSUE THREAD

**Issue by sanderclaeys** [lanl-ansi/PowerModelsDistribution.jl#188]
Most problem definitions (all except the oltc one) ignore the `fixed` parameter in the data model and consider all taps to be fixed. This fixing of the taps can be disabled by passing the flag `fix_taps=false` to constraint_mc_trans, which is `true` by default. Note that the taps should be created as well if you do not fix the taps.

Should this remain the default going forward, especially when we move to the reduced set of problem definitions?

**Comment by ccoffrin** [comment]
My feeling is that taps should be fixed taps by default.
