### ISSUE TITLE
WIP, issues to remind ourselves of

### ISSUE THREAD

**Issue by frederikgeth** [lanl-ansi/PowerModelsDistribution.jl#197]
**PMD V8.0** ~ PMs v15
- [x] consider removing multiconductorvector/matrix/value
- [x] add SDP tests (KCL vector and matrix)
- [x] variable name printing with phase index last
- [x] remove ncond from function signatures
- [x] support sm_fr dual variables?
- [x] remove unnecessary linearizations
- [x] remove unused transformer functions
- [x] remove overloading of ref

**PMD V8.1**
- [x] bus shunts are currently vectors
- [x] add unit test with capacitor bank or something else that defines a bus shunt
- [x] add transformers to IVR
- [x] add transformers to ACR

**Side task**
- [ ] drop `multiconductor=true` from `run_model` in PowerModels?

**PMD v8.2** ~ lifted extensions
- [ ] initialise lifted current variables

**PMD V9.0** ~ datamodel
- [x] high-level to low-level data model functions
- [x] low-level results to high-level results
- [x] update OpenDSS parser for new high-level data model
- [x] agree high-level data model
- [x] use current limits as default (not rate_a)
- [x] flow, current -> rename to power, current
- [ ] reference bus with just angles vs refrence bus with angles and equal magnitudes
- [x] :gen_status vs :status ?
- [x] consistent abbreviation: transformer instead of trans, capacitor instead of cap, generator vs gen
- [x] current bounds for transformers (requires discussion on transformer data model) (use existing as much as possible
- [ ] overriding OpenDSS defaults to have better default bounds, to make relaxations more useful without expert knowledge
- [x] define / agree on defaults for variables returned?
- [x] add flag to disable OpenDSS parsing of small impedances for reference bus 
- [x] capitalize parameters which are matrices? e.g. bs->Gs, r->R etc
- [x] transformer models update (eliminate some redundancy)
- [ ] extract all bound calculations to ref.jl
- [x] if not explicitly specified, make an educated guess for the base of non-dimensionalization (baseMVA, base_kv)
- [x] check if opendss can accept not documented parameters

**PMD V9.1** ~ non 4-wire updates to formulations
- [ ] add switch component math model
- [ ] big M functionality
- [ ] support transformers in LinDistFlow
- [ ] voltage sources for all formulations
- [ ] move bound calculations in IVR to ref.jl
- [ ] equal magnitudes at reference bus in ACR/ACP/IVR (constraint inconsistency)
- [x] _PMs.run_model -> PMD.run_mc_model which includes multiconductor=true, ref_extensions...., change this for all problem specs (maybe? comment that may depreciate with future PowerModels updates)

**PMD V10.0** ~ 4-wire
- [ ] JuMP dense axis arrays -> broadcasting doesn't work if variables are defined [c in cnds] vs [c in 1:ncds] (report to JuMP?)

**PMD V10.1**
- [ ] interior point initialization for non-linear speed-ups
- [ ] make sure there are no redundant @NLconstraints
- [ ] matrix variable rewrite

**PMD v10.2**
- [ ] Documentation

**Comment by sanderclaeys** [comment]
[] unify KCL pattern; ideally a function per component which defines what should be added to KCL

**Comment by sanderclaeys** [comment]
JuMP wish list
- [ ] being able to use affine expressions in NLconstraints

**Comment by sanderclaeys** [comment]
@frederikgeth do you think you will have time to integrate your lifted extensions in this or next week? Else I propose to move v8.2 to v9.2, so we first merge the new data model.

**Comment by frederikgeth** [comment]
I propose to move it, I don't expect to have time to wrap this up before you're back down-under

**Comment by pseudocubic** [comment]
It is difficult to track things this way, if there are still items missing in the Github Issues on this repo please create separate issues for them
