### ISSUE TITLE
Add unit tests for SDPWRM

### ISSUE THREAD

**Issue by pseudocubic** [lanl-ansi/PowerModelsDistribution.jl#226]
SDPWRM formulation needs some additional unit tests

**Comment by pseudocubic** [comment]
@frederikgeth was this covered in your PR #262, which was integrated into #272, or is there additional work still?

**Comment by frederikgeth** [comment]
No, those unit tests need to be added when merging in the [BIM SDP branch](https://github.com/lanl-ansi/PowerModelsDistribution.jl/tree/add-BIM-SDP-SOC). At this stage I'm not sure when I'll find the time
