### ISSUE TITLE
Agree on which variables should be reported by default

### ISSUE THREAD

**Issue by pseudocubic** [lanl-ansi/PowerModelsDistribution.jl#240]
Agree upon which variables should be reported automatically via the new solution generation infrastructure

**Comment by ccoffrin** [comment]
@frederikgeth, @sanderclaeys, can we get some elaboration on what this is about?

**Comment by frederikgeth** [comment]
This is mainly an open question for the IVR form, as we seem to have some challenges solving big cases, where the solution building takes a long time. The workaround with the expressions for the active/reactive power generator output may need to be transformed into a postprocessor

**Comment by ccoffrin** [comment]
Calling `value` on NLP expressions in JuMP is slow for some reason.  This should be fixed in the long run as NLP is updated to MOI.  Could that be the source of slow solution building?  If so, maybe the JuMP developers could propose a work around for the short term.
