### ISSUE TITLE
Buscoords parsing

### ISSUE THREAD

**Issue by pseudocubic** [lanl-ansi/PowerModelsDistribution.jl#245]
Ensure Buscoords can be parsed automatically if they are included in the dss definitions via the `buscoords` command. 

Open question: should we have a single field, `coordinates` whose value is an array `[lon, lat]`, or have two fields, `lon` and `lat`?

**Comment by ccoffrin** [comment]
I would suggest two fields to be more explicit.  But you might consider these two schemas,
```
"lat" => float,
"lon" => float 
```
and
```
{"coordinate" => {"lat" => float, "lon" => float}}
```
The former is more consistent with the other modeling conventions.
