### ISSUE TITLE
Fault Current Calculation

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModelsDistribution.jl#27]
Coordinate with Matt Reno at Sandia National Lab.

**Comment by frederikgeth** [comment]
My plan is to extend https://github.com/lanl-ansi/PowerModels.jl/pull/622 soon for the unbalanced case. Once a current-voltage formulation is in PMD.jl, defining a new problem type for fault current calculation should be straight forward. I don't really have a use case for this myself, but happy to help if there is interest.

**Comment by pseudocubic** [comment]
@bluejuniper @jtabarez

the IVR formulation will be added with #220, enabling you to add this

**Comment by bluejuniper** [comment]
Current plan is to put fault current calculations based off the IVR formulation into a separate package PowerModelsDistribution.jl
Will circulate with Matt Reno & company once tests are passing

**Comment by ccoffrin** [comment]
Agreed, we can close this issue for the time being.  Once that other package is more stable we can think about what aspects might be useful to merge into this one.
