### ISSUE TITLE
scale factors

### ISSUE THREAD

**Issue by sanderclaeys** [lanl-ansi/PowerModelsDistribution.jl#271]
@pseudocubic @ccoffrin @frederikgeth 
There are two key questions
1. Do we need scale factors for energy / impedance / admittance / cost?
2. Are scale factors implied through constituent SI units?

E.g., instead of defining an `energy_scale_factor`, we could imply implicitly
`energy_scale_factor = power_scale_factor * time_scale_factor`

However, this would also imply a scale_factor for current and impedance,
`current_scale_factor = power_scale_factor / voltage_scale_factor`,
`impedance_scale_factor = voltage_scale_factor^2 / power_scale_factor`

And we might want to define these explicitly instead.

**Comment by frederikgeth** [comment]
I prefer defining all the scale factors, but only allowing the user to define the minimal set, so that it can't be inconsistent, i.e. power, voltage, time and currency. I feel the scale factors should be implied through SI units.
