### ISSUE TITLE
Explore Use of JSON3

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModelsDistribution.jl#273]
In [this video](https://youtu.be/wF8bmLs4Za0) I learned at the long term plan is to merge the functionality of JSON and JSON3 or make JSON3 part of the standard library.  So we can consider moving to JSON3 if it brings benefits.

One feature of JSON3 that might benefit this package is its support for serializing julia types that are not natively supported in JSON data.  We should explore if this could simplify parsing are serialization of multiconductor data.

**Comment by sanderclaeys** [comment]
This seems to simplify serializing struct types, but our main issues are with serializing and deserializing
- matrices (JSON3 reads these back as a vectorization of that matrix);
- enums (JSON3 reads these back as a string);
- Bool values (not sure about JSON3);
- Inf values (not sure about JSON3);
- Array{Array{Float64}} reads as Array{Array{Any}} (not sure about JSON3);
- (@pseudocubic can you think of other issues in serializing and deserializing the data model?);

which are not resolved by the default JSON3 implementation and would similarly need customization. One way in which this could help, would be to define an intermediate transformation step, where we replace e.g. matrices which a custom struct type, which can then be persisted correctly by JSON3.

**Comment by ccoffrin** [comment]
Too bad that Matrix and ENUM do not work out of the box, maybe worth inquiring about that on discourse.  I think there should be a mechanism in JSON3 where you can overload the encoding semantics of those types
