### ISSUE TITLE
Store constraint references

### ISSUE THREAD

**Issue by tasseff** [lanl-ansi/PowerModelsDistribution.jl#277]
I have an application where I will need to reference `constraint_mc_power_balance` constraints. I've noticed that not many constraints are being stored in the `con` dictionary. Are there plans to store constraints here? Would you mind if I started making pull requests that push the constraints I need into `con`?

**Comment by pseudocubic** [comment]
It wasn’t a feature we were really using so we weren’t careful about adding constraints to `con` before, but I have nothing against it, and would definitely welcome any PRs that add those references if you need them

**Comment by ccoffrin** [comment]
Following up on this point.  I don't think this a high priority feature at the moment.  We discussed a different solution in the related application.
