### ISSUE TITLE
Multinetwork OPF and Multinetwork OPF with Storage Missing?

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModelsDistribution.jl#284]
In v0.9 I was not able to find the formulations that are equivalent to, `_run_mn_mc_opf` and `_run_mn_mc_opf_strg`, did I miss something?  

although these are not widely documented they are quite important to testing the multi-network and storage features.  An update of this example is pending the restoration of this feature. 
 https://github.com/lanl-ansi/energy-storage-example

**Comment by pseudocubic** [comment]
During the refactor of the problem types these were removed for the time being because there were no unit tests. I can prioritize adding them during the next sprint

**Comment by ccoffrin** [comment]
Great, lets get them back in.  We can use the code in the energy storage example as a basis for a unit test but I would scale it down to a smaller network with just 3 time points.
