### ISSUE TITLE
isa Array checks

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModelsDistribution.jl#303]
I still don't understand why these checks like these are required,
```
con(pm, nw, :lam_kcl_r)[i] = isa(cstr_p, Array) ? cstr_p : [cstr_p]
con(pm, nw, :lam_kcl_i)[i] = isa(cstr_q, Array) ? cstr_q : [cstr_q]
```
I suspect this fix is hiding a bug at some other place in the code.

**Comment by pseudocubic** [comment]
This is being worked on in #302
