### ISSUE TITLE
Don't error on delta loads with only one phase specified

### ISSUE THREAD

**Issue by bluejuniper** [lanl-ansi/PowerModelsDistribution.jl#309]
OpenDSS will parse these OK, I believe the behavior is to assume that the unspecified leg is connected to a solidly grounded neutral. For compatibility suggest following this behavior and generating a warning instead of error.

**Comment by frederikgeth** [comment]
Anything connected to a solidly grounded neutral would be called a wye connection in my book. We can convert such data sets, but some severe warnings would be appropriate.
