### ISSUE TITLE
parsing dss folder structures

### ISSUE THREAD

**Issue by sanderclaeys** [lanl-ansi/PowerModelsDistribution.jl#315]
I noticed some weird behaviour when redirecting to dss files at different levels of the hierarchy. Take a dss script containing the following.
```
Redirect linecodes.dss
Redirect dir/linecodes.dss
```
This imports all linecodes as expected. However, reversing the lines as follows ignores the second redirect.
```
Redirect dir/linecodes.dss
Redirect linecodes.dss
```
Is this perhaps because the parser changes directory and then thinks it is the same file, because they have the same name? Anyways, this shouldn't happen, i.e. the NREL test cases use such hierarchical files.

**Comment by pseudocubic** [comment]
Just to make sure, is this using `master` or `0.10-rc` branch?

**Comment by sanderclaeys** [comment]
This is using `master`. 

It seems like the parser ignores files with the same name as previous ones [here](https://github.com/lanl-ansi/PowerModelsDistribution.jl/blob/351c97d1fd1634d8126dbaaafe4868f683df6697/src/io/dss_parse.jl#L811).

**Comment by pseudocubic** [comment]
There was a bug that was recently fixed related to parsing filepaths that is now in `0.10-rc` branch, can you check if it is fixed there?

**Comment by sanderclaeys** [comment]
I just checked, the issue is still there in `0.10-rc`.

**Comment by pseudocubic** [comment]
ok, thanks!
