### ISSUE TITLE
documentation badge doesn't link to documentation

### ISSUE THREAD

**Issue by MartaVanin** [lanl-ansi/PowerModelsDistribution.jl#317]
Hello,
it's great to see that PMD 0.10 is out! 
This is just to let you know that if you click on the documentation badge in the main github package page, the link directs you to the badge's svg instead of the documentation. Same for the CI. I guess this isn't intentional?
I can try to fix that of the docs if you want, but I think for the CI only you have access to the exact url..

**Comment by pseudocubic** [comment]
Fixed by fe64675
