### ISSUE TITLE
Bug/enhancement: missing support for single-phase buses (v0.10.0)

### ISSUE THREAD

**Issue by MartaVanin** [lanl-ansi/PowerModelsDistribution.jl#319]
Hello,
on a similar note of #318 , if I reduce three-phase buses to single-phase buses, a number of constraints (depending on the formulation) prevents their integration in  powerflow and opf problems:
```julia
using PowerModelsDistributions, Ipopt

ipopt_solver = optimizer_with_attributes(Ipopt.Optimizer, "print_level"=>0)

data = parse_file("/test/data/opendss/case3_unbalanced.dss"; data_model = MATHEMATICAL)
delete!(data["load"], "2")
delete!(data["load"], "3")
data["bus"]["3"]["terminals"] = [2]
data["bus"]["3"]["grounded"] = Bool[0.0]
data["branch"]["1"]["t_connections"] = [2]
data["branch"]["1"]["f_connections"] = [2]
#for instance, all of the following will fail:
run_mc_pf(data, ACRPowerModel, ipopt_solver)
run_mc_pf(data, IVRPowerModel, ipopt_solver)
run_mc_opf(data, ACPPowerModel, ipopt_solver)
run_mc_opf(data, ACRPowerModel, ipopt_solver)
run_mc_opf(data, IVRPowerModel, ipopt_solver)
```
I think the option of having single-phase buses/branches is quite valuable and should be supported.
One easy way to fix that could be to broadcast of the "failing constraints" over the intersection of the component's connections. For instance, `run_mc_opf(data, ACPPowerModel, ipopt_solver)` is "blocked" by `constraint_mc_voltage_angle_difference` at:
https://github.com/lanl-ansi/PowerModelsDistribution.jl/blob/master/src/form/shared.jl#L240-L248
What could solve it could be something like the following, if you find it acceptable:
```julia
function constraint_mc_voltage_angle_difference(pm::_PM.AbstractPolarModels, nw::Int, f_idx::Tuple{Int,Int,Int}, f_connections::Vector{Int}, t_connections::Vector{Int}, angmin::Vector{<:Real}, angmax::Vector{<:Real})
    i, f_bus, t_bus = f_idx

   common_connections = intersect(f_connections, t_connections)

    va_fr = [var(pm, nw, :va, f_bus)[fc] for fc in common_connections]
    va_to = [var(pm, nw, :va, t_bus)[tc] for tc in common_connections]

    JuMP.@constraint(pm.model, va_fr .- va_to .<= angmax)
    JuMP.@constraint(pm.model, va_fr .- va_to .>= angmin)
end
```

**Comment by pseudocubic** [comment]
Thanks for the report! I definitely agree that single-phase buses and branches is a must-have, and that should largely be implemented already (with the exception of some delta connected components, which are still TODO), anything that doesn't work is something I missed in my implementation. 

I really think this is a bug; the constraint should only apply to matched conductors as it is, if the data model is valid. I will need to play around with this some more, to nail down exactly where the problem is coming from.
