### ISSUE TITLE
DCPU Problem: Formulation not being able to handle transformers 

### ISSUE THREAD

**Issue by juanjospina** [lanl-ansi/PowerModelsDistribution.jl#343]
There is a **problem (bug)** related to the `DCPU` formulation not being able to handle transformers due to an ''`MethodError: no method matching constraint_mc_transformer_power_yy(...)`

**The Error output is the following:**

![image](https://user-images.githubusercontent.com/16638960/125000475-b8873f00-e00d-11eb-9605-a2cd14c7b099.png)

**A code snippet (with a source file for the case) for replicating the problem is presented below**  :

```
using PowerModelsDistribution
import Ipopt
import JuMP

ipopt = JuMP.optimizer_with_attributes(Ipopt.Optimizer, "acceptable_tol"=>1.0e-8, "print_level"=>0, "sb"=>"yes")

pmd_file = joinpath(dirname("PowerModelsDistribution.jl/test/data/opendss/"), "case3_balanced_modmw_withoutgen.dss")

pmd_result = solve_mc_opf(pmd_file, DCPUPowerModel, ipopt)
pmd_objective = pmd_result["objective"]
pmd_solvetime = pmd_result["solve_time"]
@info "pmd objective = $pmd_objective"
@info "pmd solve time  = $pmd_solvetime"
```

**IMPORTANT**: Just make sure to add the attached case to the path `PowerModelsDistribution.jl/test/data/opendss/`

**Case**:  `case3_balanced_modmw_withoutgen.dss` (can't attach it - not supported, see source code below)

```
Clear
New Circuit.3Bus_example
!  define a really stiff source
~ basekv=230 pu=1.00 MVAsc3=200000 MVAsc1=210000

! Substation Transformer
New Transformer.SubXF Phases=3 Windings=2 Xhl=0.01
~ wdg=1 bus=sourcebus conn=wye kv=230   kva=25000    %r=0.0005
~ wdg=2 bus=Substation   conn=wye kv=13.8  kva=25000   %r=0.0005


!Define Linecodes

New linecode.556MCM nphases=3 basefreq=60  ! ohms per 5 mile
~ rmatrix = ( 0.1000 | 0.0400    0.1000 |  0.0400    0.0400    0.1000)
~ xmatrix = ( 0.0583 |  0.0233    0.0583 | 0.0233    0.0233    0.0583)
~ cmatrix = (50.92958178940651  | -0  50.92958178940651 | -0 -0 50.92958178940651  ) ! small capacitance


New linecode.4/0QUAD nphases=3 basefreq=60  ! ohms per 100ft
~ rmatrix = ( 0.1167 | 0.0467    0.1167 | 0.0467    0.0467    0.1167)
~ xmatrix = (0.0667  |  0.0267    0.0667  |  0.0267    0.0267    0.0667 )
~ cmatrix = (50.92958178940651  | -0  50.92958178940651 | -0 -0 50.92958178940651  )  ! small capacitance


!Define lines

New Line.OHLine  bus1=Substation.1.2.3  Primary.1.2.3  linecode = 556MCM   length=1  ! 5 mile line
New Line.Quad    Bus1=Primary.1.2.3  loadbus.1.2.3  linecode = 4/0QUAD  length=1   ! 100 ft


!Loads - single phase

New Load.L1 phases=1  loadbus.1.0   ( 13.8 3 sqrt / )   kW=3000   kvar=1500  model=1
New Load.L2 phases=1  loadbus.2.0   ( 13.8 3 sqrt / )   kW=3000   kvar=1500  model=1
New Load.L3 phases=1  loadbus.3.0   ( 13.8 3 sqrt / )   kW=3000   kvar=1500  model=1

Set VoltageBases = "230,13.8"
Set tolerance=0.000001
set defaultbasefreq=60
Calcvoltagebases

Solve
```

**Comment by frederikgeth** [comment]
I'd indicate this as a missing feature rather than a bug, but the feedback could be improved. May I ask why you would use this formulation? It's in PMD for historical reasons, but it's not a valid approximation for a radial and/or r \approx x network

**Comment by juanjospina** [comment]
Hi Frederik, Thank you very much for your prompt response. Nice meeting you too! I understand the DCP approximation is not a valid nor a good way to solve distribution systems. Our main use is to essentially try to integrate a DCP transmission system with a DCP solved distribution system, so both needed to be solved using the same formulation. 

I agree that this may be a feature and not a bug. Thanks again for the help.
