### ISSUE TITLE
DCPU Problem: Many cases from the /test/data/opendss/ folder not being solved (UNFEASIBLE)

### ISSUE THREAD

**Issue by juanjospina** [lanl-ansi/PowerModelsDistribution.jl#344]
There seems to be a problem (bug) related to the DCPU formulation **not** being able to **solve** (find a **feasible point** - using ipopt) many cases available from `/test/data/opendss/` repository. Other formulations (ACR, ACP, etc) **do work** fine.

**Some of the cases tested that fail (`"termination_status" => LOCALLY_INFEASIBLE`) are:**
1. `case_mxshunt.dss`
2. `case3_balanced.dss`
3. `case3_unbalanced.dss`
4. `case3_lm_1230.dss`
5. `case3_balanced_basefreq.dss`

**However**, some other cases do **work**:
1. `case4_phase_drop.dss`
2. `case5_phase_drop.dss`

**A code snippet for replicating the problem is presented below**:

```
using PowerModelsDistribution
import Ipopt
import JuMP

ipopt = JuMP.optimizer_with_attributes(Ipopt.Optimizer, "acceptable_tol"=>1.0e-8, "print_level"=>5, "print_info_string"=>"yes", "sb"=>"yes") 

pmd_file = joinpath(dirname(""PowerModelsDistribution.jl/test/data/opendss/""), "case3_balanced.dss")

pmd_result = solve_mc_opf(pmd_file, DCPUPowerModel, ipopt)
pmd_objective = pmd_result["objective"]
pmd_solvetime = pmd_result["solve_time"]
@info "$pmd_result"
@info "pmd objective = $pmd_objective"
@info "pmd solve time  = $pmd_solvetime"
```

**Comment by frederikgeth** [comment]
There may be bugs hiding somewhere, but infeasibility may be the correct output, given how none of the networks satisfy the assumptions that went into the unbalanced extension of the DC linearization. See https://dl.acm.org/doi/abs/10.1145/3447555.3464875 for some background.

**Comment by juanjospina** [comment]
Thank you very much for the great paper suggestion Frederik. I will take a look at it. You are correct that the problem may be related to the case itself and not PMD.
