### ISSUE TITLE
Problem with IVRUPowerModel when solving problems with Transformers [BUG]

### ISSUE THREAD

**Issue by juanjospina** [lanl-ansi/PowerModelsDistribution.jl#371]
**Describe the bug**

There seems to be a bug/problem that causes IVRUPowerModel cases that have transformers (or at least a Substation transformer) to be infeasible (ipopt enters in a restoration phase). The problem was introduced in v0.13.0 since the problem is solved correctly when using v0.12.0.

The bug/problem seems to be related to a modification in the transformers' constraints in v0.13.0 because when the transformer(s) is removed, the case solves correctly.

**Minimum Viable Example**

Steps to reproduce the behavior. The following code was used to verify the bug/problem.

```
using PowerModelsDistribution
import Ipopt
import JuMP

ipopt = JuMP.optimizer_with_attributes(Ipopt.Optimizer, "acceptable_tol"=>1.0e-8, "print_level"=>5, "sb"=>"yes")

pmd_data = parse_file("case3_balanced_withTransformer.dss")
# pmd_data = parse_file("case3_balanced_noTransformer.dss")

result_pmd = solve_mc_opf(pmd_data, IVRUPowerModel, ipopt)

```

The test cases (i.e., `.dss` files) are added in the **Additional context** section.

**Expected behavior**

Both cases (with and without transformers) should be solved correctly (both problems are feasible).

**Screenshots**

Screenshot of the ipopt output when solving the case with transformer:

![image](https://user-images.githubusercontent.com/16638960/142457424-6f2f3af1-fdb7-4a0c-a4ca-079653b09313.png)

**System Information (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Version 0.13.0

**Additional context**
Other formulations such as ACPU, ACRU solve both cases (i.e., with and without transformers), that is why the problem seems to be related to the IVRU formulation only. The files used for the test cases are given below.

- `case3_balanced_withTransformer.dss`:

```
!Clear

New Circuit.3Bus_example
!  define a really stiff source
~ basekv=230 pu=1.00 MVAsc3=200000 MVAsc1=210000

! Substation Transformer
New Transformer.SubXF Phases=3 Windings=2 Xhl=0.01
~ wdg=1 bus=sourcebus conn=wye kv=230   kva=25000    %r=0.0005
~ wdg=2 bus=Substation   conn=wye kv=13.8  kva=25000   %r=0.0005

!Define Linecodes

New linecode.556MCM nphases=3 basefreq=60  ! ohms per 5 mile
~ rmatrix = ( 0.1000 | 0.0400    0.1000 |  0.0400    0.0400    0.1000)
~ xmatrix = ( 0.0583 |  0.0233    0.0583 | 0.0233    0.0233    0.0583)
~ cmatrix = (50.92958178940651  | -0  50.92958178940651 | -0 -0 50.92958178940651  ) ! small capacitance

New linecode.4/0QUAD nphases=3 basefreq=60  ! ohms per 100ft
~ rmatrix = ( 0.1167 | 0.0467    0.1167 | 0.0467    0.0467    0.1167)
~ xmatrix = (0.0667  |  0.0267    0.0667  |  0.0267    0.0267    0.0667 )
~ cmatrix = (50.92958178940651  | -0  50.92958178940651 | -0 -0 50.92958178940651  )  ! small capacitance

!Define lines

New Line.OHLine  bus1=Substation.1.2.3  Primary.1.2.3  linecode = 556MCM   length=1 normamps=6000 emergamps=6000 ! 5 mile line
New Line.Quad    Bus1=Primary.1.2.3  loadbus.1.2.3  linecode = 4/0QUAD  length=1  normamps=6000 emergamps=6000 ! 100 ft

!Loads - single phase

New Load.L1 phases=1  loadbus.1.0   ( 13.8 3 sqrt / )   kW=30   kvar=15  model=1
New Load.L2 phases=1  loadbus.2.0   ( 13.8 3 sqrt / )   kW=30   kvar=15  model=1
New Load.L3 phases=1  loadbus.3.0   ( 13.8 3 sqrt / )   kW=30   kvar=15  model=1

Set VoltageBases = "230,13.8"
Set tolerance=0.000001
set defaultbasefreq=60

```

- `case3_balanced_noTransformer.dss`:

```
!Clear

New Circuit.3Bus_example
!  define a really stiff source
~ basekv=13.8 pu=1.00 MVAsc3=200000 MVAsc1=210000

!Define Linecodes

New linecode.556MCM nphases=3 basefreq=60  ! ohms per 5 mile
~ rmatrix = ( 0.1000 | 0.0400    0.1000 |  0.0400    0.0400    0.1000)
~ xmatrix = ( 0.0583 |  0.0233    0.0583 | 0.0233    0.0233    0.0583)
~ cmatrix = (50.92958178940651  | -0  50.92958178940651 | -0 -0 50.92958178940651  ) ! small capacitance

New linecode.4/0QUAD nphases=3 basefreq=60  ! ohms per 100ft
~ rmatrix = ( 0.1167 | 0.0467    0.1167 | 0.0467    0.0467    0.1167)
~ xmatrix = (0.0667  |  0.0267    0.0667  |  0.0267    0.0267    0.0667 )
~ cmatrix = (50.92958178940651  | -0  50.92958178940651 | -0 -0 50.92958178940651  )  ! small capacitance

!Define lines

New Line.OHLine  bus1=sourcebus.1.2.3  Primary.1.2.3  linecode = 556MCM   length=1 normamps=6000 emergamps=6000 ! 5 mile line
New Line.Quad    Bus1=Primary.1.2.3  loadbus.1.2.3  linecode = 4/0QUAD  length=1  normamps=6000 emergamps=6000 ! 100 ft

!Loads - single phase

New Load.L1 phases=1  loadbus.1.0   ( 13.8 3 sqrt / )   kW=30   kvar=15  model=1
New Load.L2 phases=1  loadbus.2.0   ( 13.8 3 sqrt / )   kW=30   kvar=15  model=1
New Load.L3 phases=1  loadbus.3.0   ( 13.8 3 sqrt / )   kW=30   kvar=15  model=1

Set VoltageBases = "13.8"
Set tolerance=0.000001
set defaultbasefreq=60

```

**Comment by pseudocubic** [comment]
It seems the issue is related to `sm_ub` on transformers which is now parsed from dss transformers from the dss property `emerghkva`. Previously, this value was always `Inf`, and therefore there were no bounds on transformers.

I think the issue is here: https://github.com/lanl-ansi/PowerModelsDistribution.jl/blob/main/src/core/data.jl#L435-L436

In particular, it should be `./vmin` not `vmax`. In this specific case because `vmax=Inf` by default, so the upper and lower bounds on transformer current will be `0`

While you wait for a fix, you can use the function `remove_transformer_limits!` to fix the problem.
