### ISSUE TITLE
[BUG] JuMP 0.22 incompatible with PolyhedralRelaxations 0.3.1

### ISSUE THREAD

**Issue by MartaVanin** [lanl-ansi/PowerModelsDistribution.jl#374]
Hello,
I would like to discontinue support for JuMP 0.21 in PowerModelsDistributionStateEstimation.jl, and exclusively allow JuMP 0.22. This is because I need some functionalities of JuMP 0.22 in some package downstream. 
However, I cannot do that because PowerModelsDistributionStateEstimation.jl depends on PowerModelsDistribution.jl, which depends on PolyhedralRelaxations 0.3.1, which in turn does not allow for JuMP 0.22.
I reckon you might at some point want to remove support for JuMP 0.21 for PowerModelsDistribution, too, so decided to ask here first. What are your thought on this? Should I just try and bring this up with the PolyhedralRelaxations people (I don't know them)?

**Comment by MartaVanin** [comment]
short update: I opened a (PR in PolyhedralRelaxations)[https://github.com/sujeevraja/PolyhedralRelaxations.jl/pull/9]

**Comment by pseudocubic** [comment]
Thanks @MartaVanin, I will try to follow-up offline with that team as well to see what the ETA is

**Comment by MartaVanin** [comment]
This is now solved in principle, as PolyhedralRelaxations released [v0.3.2](https://github.com/sujeevraja/PolyhedralRelaxations.jl/commit/427b91e4c4ba3e551a908ed4b0b1e9a78811dba4). PowerModelsDistribution is already compatible with the new PolyhedralRelaxations, as it is bounded as "~0.3.1". However, this might have broken a couple of PowerModelsDistribution's tests. These now fail on my (windows) machine, as they run with JuMP 0.22.

**Comment by pseudocubic** [comment]
@MartaVanin I am actively working on the tests thing. I believe it is actually due to the Ipopt update, which implies a numerical instability in the tests. I think I will have an update in the main branch sometime today though.

**Comment by ccoffrin** [comment]
FYI, I noticed recent changes in JuMP/Ipopt in the last week did make some very minor changes some tests in some of the InfrastructureModels tests.

https://github.com/lanl-ansi/InfrastructureModels.jl/commit/7f27cae5011eec9e14f74bbf244d979d1524ae78

CC @odow

**Comment by MartaVanin** [comment]
> @MartaVanin I am actively working on the tests thing. I believe it is actually due to the Ipopt update, which implies a numerical instability in the tests. I think I will have an update in the main branch sometime today though.

I see, thanks. This tests thing is not blocking/preventing me from doing anything, so not in a hurry here. Just wanted to let you know, although apparently you already did :)

**Comment by odow** [comment]
We bumped Ipopt from 3.13.4 to 3.14.4 and MUMPS from 5.2.1 to 5.4.1, so I assume that is the cause for numerical differences.
