### ISSUE TITLE
Using pyjulia with PMD -- ImportError

### ISSUE THREAD

**Issue by apigott** [lanl-ansi/PowerModelsDistribution.jl#391]
I'm trying to include PMD in a bit of Python however I'm running into issues with the import of PMD to Python. I'm relatively new to Julia but I'm able to import other Julia functions to Python without issue so I'm not sure if it's specific to PMD. I've tried the following which results in an import error:

```
from julia import Pkg
Pkg.activate("C:/Users/Aisling/.julia/environments/pmd")
from julia.PowerModelsDistribution import solve_mc_opf
```
```
ImportError                               Traceback (most recent call last)
<ipython-input-27-6e83bbbb609c> in <module>
----> 1 from julia.PowerModelsDistribution import solve_mc_opf

C:\ProgramData\Anaconda3\lib\site-packages\julia\core.py in load_module(self, fullname)
    258                                               JuliaModule(self, fullname))
    259 
--> 260         raise ImportError("{} not found".format(juliapath))
    261 
    262 

ImportError: PowerModelsDistribution.solve_mc_opf not found
```

Am I misunderstanding the structure of PMD or has anyone else successfully imported PMD functions?

**Comment by MartaVanin** [comment]
hi, I don't have pyjulia set up to try this, but, just to be sure, what version of PMD do you have in your environment? because in the past `solve_`... functions were called `run_`... functions, so maybe it's just that?

**Comment by apigott** [comment]
Hm. The same method that fails with PMD works with a package like StatsBase though I could try others. `from julia import PowerModelsDistribution` runs without errors but interestingly calling `dir(PowerModelsDistribution)` doesn't return any of the functions. It returns `['__doc__', '__loader__', '__name__', '__package__', '__spec__', '_julia']`.

Whereas `from julia import StatsBase` `dir(StatsBase)` would return a long list of functions within the module. 

I'll leave this open for now while I look into it.

**Comment by MartaVanin** [comment]
that's interesting. then maybe it does have to do with how PowerModelsDistribution exports its functions. StatsBase explicitly exports them: https://github.com/JuliaStats/StatsBase.jl/blob/master/src/StatsBase.jl#L35

whereas pmd does it like this: https://github.com/lanl-ansi/PowerModelsDistribution.jl/blob/main/src/core/export.jl 
maybe pyjulia doesn't pick it up?

**Comment by apigott** [comment]
Hm. I couldn't replace this in scripted Python (only in a Jupyter notebook) which doesn't really seem satisfying as it should import the PMD module properly in either place (as other modules can be imported from either). For now I'll close with the suggestion that anyone else trying this just work in scripted Python.
