### ISSUE TITLE
Confusing lack of documentation for adding storage

### ISSUE THREAD

**Issue by apigott** [lanl-ansi/PowerModelsDistribution.jl#392]
I'm trying to modify the "Extending PowerModelsDistribution" tutorial with an EV modeled as a load + generator -- replacing the load + generator with a storage component because it suits my problem to have the "load" be controllable as well. However, replacing the code block that adds a generator component with one that adds storage is resulting in the following error

```
# including all specifications outlined in the docs under Eng Data Model > Storage
begin
	data_eng["storage"] = Dict{String, Any}()
	for e in EVs
		data_eng["storage"]["EV_stor_$e"] = Dict{String, Any}(
			"status" => PMD.ENABLED,
			"bus" => bus_e[e],
			"connections" => [phase_e[e], 4],
			"configuration" => PMD.WYE,
			"energy" => 20,
			"qs_ub" => 10,
			"qs_lb" => -10,
			"energy_ub" => 100,
			"charge_ub" => 20,
			"discharge_ub" => 20,
			"charge_efficiency" => 0.97,
			"discharge_efficiency" => 0.95,
			"rs" => 1,
			"xs" => 1,
			"pex" => 0.1,
			"qex" => 0.1,
			"cm_ub" => 10,
			"sm_ub" => 20,
		)
	end
end;

data_math_mn = transform_data_model(data_eng, multinetwork=true);

add_start_vrvi!(data_math_mn);

pm = PMD.instantiate_mc_model(data_math_mn, PMD.IVRUPowerModel, PMD.build_mn_mc_opf);
```
Errror message: 
```
real currentr decision variables appear to be missing for storage components

    error(::String)@error.jl:33
    _check_var_keys(::Dict{Any, Any}, ::Vector{Tuple{Int64, Vector{Int64}}}, ::String, ::String)@base.jl:67
    constraint_mc_current_balance(::PowerModelsDistribution.IVRUPowerModel, ::Int64, ::Int64, ::Vector{Int64}, ::Vector{Bool}, ::Vector{Tuple{Tuple{Int64, Int64, Int64}, Vector{Int64}}}, ::Vector{Tuple{Tuple{Int64, Int64, Int64}, Vector{Int64}}}, ::Vector{Tuple{Tuple{Int64, Int64, Int64}, Vector{Int64}}}, ::Vector{Tuple{Int64, Vector{Int64}}}, ::Vector{Tuple{Int64, Vector{Int64}}}, ::Vector{Tuple{Int64, Vector{Int64}}}, ::Vector{Tuple{Int64, Vector{Int64}}})@ivr.jl:275
    var"#constraint_mc_current_balance#2508"(::Int64, ::typeof(PowerModelsDistribution.constraint_mc_current_balance), ::PowerModelsDistribution.IVRUPowerModel, ::Int64)@constraint_template.jl:393
    build_mn_mc_opf(::PowerModelsDistribution.IVRUPowerModel)@opf.jl:492
    var"#instantiate_model#23"(::Vector{Function}, ::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, ::typeof(InfrastructureModels.instantiate_model), ::Dict{String, Any}, ::Type, ::typeof(PowerModelsDistribution.build_mn_mc_opf), ::typeof(PowerModelsDistribution.ref_add_core!), ::Set{String}, ::Symbol)@base.jl:370
    var"#instantiate_mc_model#3330"(::Vector{Function}, ::Bool, ::Set{String}, ::Vector{Function}, ::Dict{String, Vector{String}}, ::Vector{Function}, ::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, ::typeof(PowerModelsDistribution.instantiate_mc_model), ::Dict{String, Any}, ::Type, ::typeof(PowerModelsDistribution.build_mn_mc_opf))@common.jl:119
    instantiate_mc_model(::Dict{String, Any}, ::Type, ::Function)@common.jl:107
    top-level scope@[Local: 1](http://localhost:1234/edit?id=d0ae4830-06ea-11ed-0e51-6d4f6889fafb#)[inlined]
```

Is this an issue with missing parameters or can I not add a storage component to the eng data model in the same way you can add a generator? (Also the docs reference this not including an inverter "similar to PV" but it seems like the inverter might be modeled implicitly from reading other issues and because I couldn't find any other references to an inverter model in the docs but please let me know if that's a misunderstanding.)

**Comment by pseudocubic** [comment]
I don't see any issues with the storage object you created; in this case, I think the problem is that unfortunately storage is not supported in the IVRU formulation currently.

**Comment by apigott** [comment]
Thanks for the reply and apologies for the delayed response while I try to sort this out. Changing the formulation to ACPUPowerModel fixed that issue but `pm = PMD.instantiate_mc_model(data_math_mn, PMD.ACRUPowerModel, PMD.build_mn_mc_opf);` came back with another error that the time elapsed argument was of unmatched type `int`. 

To fix that error I changed the following by casting the time, k, as a float:
```
begin
	data_eng["time_series"] = Dict{String, Any}()
	data_eng["time_series"]["normalized_load_profile"] = Dict{String, Any}(
		"replace"=>false,
		"time"=>float(K),
		"values"=>0.2*cos.((pi/2/maximum(K)).*K)
	)
end
```

Unfortunately this is still creating errors as the powermodel multi-network doesn't have the correct time keys when trying to link the variable in JuMP with the PMD var. My best guess was that casting the time value as a float was causing the keys of the multi-network to also be floats or incorrectly created somehow but I can't seem to figure it out: 
```
KeyError: key 1 not found

    getindex(::Dict{Int64, Any}, ::Int64)@dict.jl:481
    var(::PowerModelsDistribution.ACRUPowerModel, ::Symbol, ::Int64, ::Symbol, ::Int64)@base.jl:289
    var(::PowerModelsDistribution.ACRUPowerModel, ::Int64, ::Symbol, ::Int64)@base.jl:36
    (::var"#61#63"{PowerModelsDistribution.ACRUPowerModel, Vector{Int64}, Module})(::Tuple{Int64, Int64})@none:0
    iterate@generator.jl:47[inlined]
    collect(::Base.Generator{Base.Iterators.ProductIterator{Tuple{Vector{Int64}, UnitRange{Int64}}}, var"#61#63"{PowerModelsDistribution.ACRUPowerModel, Vector{Int64}, Module}})@array.jl:724
    top-level scope@[Local: 2](http://localhost:1234/edit?id=7b3f8dc0-0ba7-11ed-287b-c54236e1177a#)[inlined]
```

```
begin
	nc_Ps_ek = [PMD.var(pm, k, :ps, ev_stor_ind_e[e]).data[1] for e in EVs, k in K]
	nc_Qs_ek = [PMD.var(pm, k, :qs, ev_stor_ind_e[e]).data[1] for e in EVs, k in K]
end;
```

If there's any docs that explain the storage in a multi-network ACOPF that'd be great too I just couldn't find any in the current docs.

**Comment by apigott** [comment]
To correct that earlier comment, `pm.var.keys` are all `#undef`. It seems like that implies `pm=PMD.instantiate_mc_model(data_math_mn, PMD.ACPUPowerModel, PMD.build_mn_mc_opf)` fails then, I'm not sure why that'd be

**Comment by pseudocubic** [comment]
Casting as float should not be required, so that is a bug that I should fix.

Your second reply just now rang a bell for me, and I think the problem is that you are missing a multinetwork keyword argument in `instantiate_mc_model`, since it does not detect whether the data is multinetwork automatically. I think it should be 

`pm=PMD.instantiate_mc_model(data_math_mn, PMD.ACPUPowerModel, PMD.build_mn_mc_opf; multinetwork=true)`

That being said, I think I can add this ability to check if the data is multinetwork, while giving users the ability to override it.

One other thing is that the keys for `nw` will not necessarily match the values in `K`. We assign sequential integer values to `nw`, whose actual time step can be looked-up in `mn_lookup`. Therefore, in your last code block, you should iterate over `nw` using the functio nw_ids, like so:

```julia
begin
	nc_Ps_ek = [PMD.var(pm, k, :ps, ev_stor_ind_e[e]).data[1] for e in EVs, k in nw_ids(pm)]
	nc_Qs_ek = [PMD.var(pm, k, :qs, ev_stor_ind_e[e]).data[1] for e in EVs, k in nw_ids(pm)]
end;
```

See for example: https://github.com/lanl-ansi/PowerModelsDistribution.jl/blob/main/src/core/objective.jl#L47

**Comment by apigott** [comment]
Thanks so much! Both those fixes (plus patching the time/float issue) solved the issue and my model is running, so I'll go ahead and close this issue now
