### ISSUE TITLE
[FEATURE] Multi-network OPF for capacitor control?

### ISSUE THREAD

**Issue by apigott** [lanl-ansi/PowerModelsDistribution.jl#403]
**Is your feature request related to a problem? Please describe.**
I'm trying to run a multi-timestep OPF that utilizes a set of capacitor banks. Of course `build_mn_mc_opf` and `build_mc_opf_capc` exist but I couldn't find `build_mn_mc_opf_capc`

**Describe the solution you'd like**
Here's the build_mn_mc_opf_capc that I used locally based off `build_mn_mc_opf` and `build_mc_opf_capc`. It builds properly but my test network isn't solving (converges to a point of infeasibility -- I think the loading is wrong). 
```
function build_mn_mc_opf_capc(pm::AbstractUnbalancedPowerModel)
    for (n, network) in nws(pm)
        variable_mc_bus_voltage(pm; nw=n)
        variable_mc_branch_power(pm; nw=n)
        variable_mc_switch_power(pm; nw=n)
        variable_mc_transformer_power(pm; nw=n)
        variable_mc_generator_power(pm; nw=n)
        variable_mc_load_power(pm; nw=n)
        variable_mc_storage_power(pm; nw=n) # missing from capc
		variable_mc_capcontrol(pm; nw=n, relax=true)

        constraint_mc_model_voltage(pm; nw=n)

        for i in ids(pm, n, :ref_buses)
            constraint_mc_theta_ref(pm, i; nw=n)
        end

        for id in ids(pm, n, :gen)
            constraint_mc_generator_power(pm, id; nw=n)
        end

        for id in ids(pm, n, :load)
            constraint_mc_load_power(pm, id; nw=n)
        end

        for i in ids(pm, n, :bus)
            constraint_mc_power_balance(pm, i; nw=n)
        end

        for i in ids(pm, n, :storage)
            constraint_storage_complementarity_nl(pm, i; nw=n)
            constraint_mc_storage_losses(pm, i; nw=n)
            constraint_mc_storage_thermal_limit(pm, i; nw=n)
        end

        for i in ids(pm, n, :branch)
            constraint_mc_ohms_yt_from(pm, i; nw=n)
            constraint_mc_ohms_yt_to(pm, i; nw=n)
            constraint_mc_voltage_angle_difference(pm, i; nw=n)
            constraint_mc_thermal_limit_from(pm, i; nw=n)
            constraint_mc_thermal_limit_to(pm, i; nw=n)
            constraint_mc_ampacity_from(pm, i; nw=n)
            constraint_mc_ampacity_to(pm, i; nw=n)
        end

        for i in ids(pm, n, :switch)
            constraint_mc_switch_state(pm, i; nw=n)
            constraint_mc_switch_thermal_limit(pm, i; nw=n)
            constraint_mc_switch_ampacity(pm, i; nw=n)
        end

        for i in ids(pm, n, :transformer)
            constraint_mc_transformer_power(pm, i; nw=n)
        end
    end

    network_ids = sort(collect(nw_ids(pm)))

    n_1 = network_ids[1]

    for i in ids(pm, :storage; nw=n_1)
        constraint_storage_state(pm, i; nw=n_1)
    end

    for n_2 in network_ids[2:end]
        for i in ids(pm, :storage; nw=n_2)
            constraint_storage_state(pm, i, n_1, n_2)
        end

        n_1 = n_2
    end

    objective_mc_min_fuel_cost(pm)
end
```

**Describe alternatives you've considered**

**Additional context**
Related: The test case for the capc formulation in PMD fails out of the box for me -- anyone else have this issue and/or any notes on how to get this to solve correctly? (Also fails in polar coords)

ETA: Fails by converging to an infeasible point in ACPUPowerModel, ACRUPowerModel, and fails because it isn't supported in IVRUPowerModel (my bad)

```
data_eng = PMD.parse_file(
	"../PowerModelsDistribution.jl/test/data/opendss/IEEE13_CapControl.dss",
	transformations=[PMD.remove_all_bounds!]
);
solve_mc_opf_capc(data_eng, ~~IVRUPowerModel~~ ACPUPowerModel, Ipopt.Optimizer)
```

Thanks!

**Comment by pseudocubic** [comment]
We have an implementation of a multinetwork OPF that includes both regcontrol and capcontrol support in [PowerModelsONM](https://github.com/lanl-ansi/PowerModelsONM.jl/blob/main/src/prob/opf.jl). 

That said, @keatsig will be taking a closer look at your particular use case.

**Comment by apigott** [comment]
@pseudocubic good to know, I'll look into switching to -ONM. It seems like there are a lot of PowerModels based packages even just out of LANL; is there any centralized documentation of which package is suited to what problems or is it more trial and error?

**Comment by pseudocubic** [comment]
Unfortunately, we don't have a cheat-sheet to point people the the right package right now, though that is a good idea. 

PowerModelsONM in particular is being used for a specific project still in-progress, and is an extension to PowerModelsDistribution for solving load shed problems for distribution feeders. Unless you need that functionality in particular, I think just copying the problem specifications directly from the file I linked will be enough for your use case.

**Comment by keatsig** [comment]
@apigott it looks like the `build_mn_mc_opf_capc` function above is using `constraint_mc_power_balance` instead of `constraint_mc_power_balance_capc.` This could be one of the reasons for the local infeasibility issue.

Also, PMD fails out of the box for IVR formulation since CapControl was only implemented for ACP, ACR, FOT, FBS and LinDist3Flow formulations. I have opened a PR to add CapControl for IVR formulation.

**Comment by apigott** [comment]
@keatsig This is poor note taking on my part. I remembered Fred telling me it wasn't formulated for one of them (so it makes sense that that's the error about missing :crg for IVR). However, as noted it fails out of the box for ACP as well, and actually I left out that it _also_ fails in ACR for me too ("converge to point of local infeasibility"). Do those formulations run for you?

**Comment by keatsig** [comment]
Yes, the other formulations with CapControl do run without infeasibility issues for the IEEE13_CapControl case. When you run `test PowerModelsDistribution`, do all the unit tests pass?

Regarding the IEEE13 test case with half the network, the file name might be misleading! The original IEEE13 test case was modified to get a small and simple test case for unit testing purposes (to check the capacitor control implementation).

**Comment by apigott** [comment]
Yes `Pkg.test("PowerModelsDistribution")` passes. Are you doing any transformations to the network before solving it? Warm starting it? Using something other than Ipopt (v1.1.0)?
