### ISSUE TITLE
[BUG] Joining lines calls a function which throws an error

### ISSUE THREAD

**Issue by hei06j** [lanl-ansi/PowerModelsDistribution.jl#416]
In the network reduction by joining lines, the line 1338 with link below will throw an error if comp["bus"] in line 1334 is not a string, as it attempts to append an integer to a vector of strings.
https://github.com/lanl-ansi/PowerModelsDistribution.jl/blob/7188b0fd0c5f4410fce284f861b30ae679f731b8/src/data_model/transformations.jl#L1338 

https://github.com/lanl-ansi/PowerModelsDistribution.jl/blob/7188b0fd0c5f4410fce284f861b30ae679f731b8/src/data_model/transformations.jl#L1334

error:
```
ERROR: MethodError: Cannot `convert` an object of type Int64 to an object of type String
```

I assume replacing the last argument in line 1334 with `[string(comp["bus"])]` would fix the problem.

**Comment by pseudocubic** [comment]
I actually think that the correct way to fix this is to rewrite the line to check if `isa(comp["bus"], Vector)`. 

That said, I'm not clear on how we would end up with non-string bus names, could you provide a small example so that we can add a unit test?

**Comment by hei06j** [comment]
Actually you are correct. I encountered this error when I used the join_line code (with necessary modifications) to reduce a network in PowerModels.jl rather than PMD.jl. So given that this code works with data_eng and all assets have the key "bus" as string, my original bug is not valid here. Thanks for the clarification. But the vector check makes sense.
