### ISSUE TITLE
Default Rates in OpenDSS Parser

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModelsDistribution.jl#56]
If no `normamps` is provided, I think we should set the rate parameters to zero, so that `check_thermal_limits` can define a resonable value, otherwise we risk overly restrictive thermal limits in an OPF.  Is that the current semantics?

**Comment by pseudocubic** [comment]
Currently, rates are set to `400, 600, 600`, for `rate_a, rate_b, rate_c`, respectively. This is because when no `normamps` or `emergamps` are specified, OpenDSS assumes them to be `400` and `600`, respectively.

**Comment by ccoffrin** [comment]
Got it.  I think should be an exception to our standard semantics for defaults.  The root of the issue is that OpenDSS is not solving OPF, so these rates will not impact solution feasibility.  Because we are solving OPF we have to be much more careful about how we set rates as to not be overly restrictive.

One option would be to simply not interoperate `normamps` and `emergamps` as rates and always set the rates to 0 in the parser and let users specify `import_all`, if they want to leverage these parameters.

**Comment by pseudocubic** [comment]
Depends on PowerModels Issue [#338](https://github.com/lanl-ansi/PowerModels.jl/issues/338)
