### ISSUE TITLE
Harmonize formulation names, e.g. SOCBFPowerModel

### ISSUE THREAD

**Issue by frederikgeth** [lanl-ansi/PowerModelsDistribution.jl#58]
Currently the `SOCBFPowerModel` is an implementation of a linear approximation of branch flow model, not a convex relaxation.

Per the guidelines [here](https://github.com/lanl-ansi/ThreePhasePowerModels.jl/pull/57), the name should be updated:

> - Give the formulations names that are reminiscent of the original source paper, add a doc string citation to the formulation type definition
> - Indicate in the doc string if the formulation is an approximation or a relaxation
> - Generally use subtypes of the formulations in PowerModes. Notable exceptions would be ACP or ACR which have clear multi-phase analogs

**Comment by pseudocubic** [comment]
Per our discussions, suggest to add full formulation names as we have been doing, but also to add alias to accepted formulation names, e.g. LPUBFDiagModel is aliased to LinDist3FlowModel

**Comment by pseudocubic** [comment]
This seems completed to me, is there additional work still to be done? @frederikgeth

**Comment by ccoffrin** [comment]
If possible, I would recomend utilizing the BFA type name from PowerModels for one of the formulations.

**Comment by frederikgeth** [comment]
I think this issue can be closed after addressing Carleton's point on the BFA form (i.e. LPDiag).
