### ISSUE TITLE
Matlab Based Network Data Format

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModelsDistribution.jl#80]
Update the Matlab based data format based on discussions with @frederikgeth.

Requires completion of https://github.com/lanl-ansi/ThreePhasePowerModels.jl/issues/79.

**Comment by pseudocubic** [comment]
We should discuss how to best implement transformers into this format

**Comment by ccoffrin** [comment]
Notes from this discussion,
- this format will only support a simple academic-centric model of transformers
- transformers components will have an analog to line codes for the bulk of their settings

**Comment by pseudocubic** [comment]
Will revisit if there ends up being a three phase matpower format
