### ISSUE TITLE
Update Problem Formulations

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModelsDistribution.jl#81]
Make sure that all problem formulations are using the same `TP` constraints, especially in `tp_opf`.

**Comment by pseudocubic** [comment]
Has this issue been resolved? I'm not sure what exactly you're looking for here. I checked through all of the problem formulations and they all seem to consistently use `_tp_` constraints as far as I can tell.

**Comment by ccoffrin** [comment]
This is related to #61, we can put both into a general milestone on revisiting the modeling layer; but this is not a high priority at the moment.
